services=ranger-admin:1:cldb
service.displayname=RangerAdmin
service.command.start=/opt/mapr/ranger/ranger-2.4.0/ranger-admin/ews/ranger-admin-services.sh start
service.command.stop=/opt/mapr/ranger/ranger-2.4.0/ranger-admin/ews/ranger-admin-services.sh stop
service.command.type=BACKGROUND
service.command.monitorcommand=/opt/mapr/ranger/ranger-2.4.0/ranger-admin/ews/ranger-admin-services.sh status
service.port=6182
service.ui.port=6182
service.logs.location=/opt/mapr/ranger/ranger-2.4.0/ranger-admin/ews/logs
service.process.type=JAVA
service.alarm.tersename=ranger-admin
service.alarm.label=RangerAdminDown
