services=ranger-usersync:1:ranger-admin
service.displayname=RangerUserSync
service.command.start=/opt/mapr/ranger/ranger-2.4.0/ranger-usersync/ranger-usersync-services.sh start
service.command.stop=/opt/mapr/ranger/ranger-2.4.0/ranger-usersync/ranger-usersync-services.sh stop
service.command.type=BACKGROUND
service.command.monitorcommand=/opt/mapr/ranger/ranger-2.4.0/ranger-usersync/ranger-usersync-services.sh status
service.port=5151
service.ui.port=5151
service.logs.location=/opt/mapr/ranger/ranger-2.4.0/ranger-usersync/logs
service.process.type=JAVA
service.alarm.tersename=ranger-usersync
service.alarm.label=RangerUserSyncDown
